### ISSUE TITLE
Is it working correctly?

### ISSUE THREAD

**Issue by kootenpv** [antequant/ib-gateway-docker#5]
Just wondering because of the slight disclaimer :)

I am seeing other versions with socat and eventually I end up with an issue:

    socat[537] E connect(5, AF=2 127.0.0.1:4001, 16): Connection refused

It appears it has difficulty connecting to the gateway. Just checking... is this working in a stable manner for you?

**Comment by jspahrsummers** [comment]
Sorry, I haven't been deploying it recently--but the last tagged version did consistently work for me.

**Comment by gp-slick-coder** [comment]
Is working fine for me. 👍 🥇

**Comment by ashishnitinpatil** [comment]
Working fine for me too. Accidentally changed the port in the `ini`, and it wasn't connecting, but reverting back to 4001 I was able to connect.

Note: I'm using the [stable standalone](https://download2.interactivebrokers.com/installers/ibgateway/stable-standalone/ibgateway-stable-standalone-linux-x64.sh) instead of latest standalone IB gateway, with latest IBC (3.8.4-beta.2)
